name: Playwright Tests

on:
  push:
    branches: [main] # trigger when code is pushed to main branch
  pull_request:
    branches: [main] # trigger when PR is created to main branch
  workflow_dispatch: # manual trigger from GitHub UI

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest # Linux machine (most common in CI)
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # pulls your repo code into runner

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # install Node.js version

      - name: Install dependencies
        run: npm ci # clean install (faster + reliable for CI)

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
        # installs browser + required Linux dependencies

      - name: Run tests
        run: npx playwright test --project=chromium
        env:
          ENV: qa
          BASE_URL: ${{ secrets.BASE_URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report/
          retention-days: 30

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
          retention-days: 30
